/* Question bank — tailored to Aakash Siwach's resume.
   Each item: id, category, difficulty (easy|medium|hard), question, answerEn (HTML), answerHi (HTML), optional code.
   Add your own questions by copying an object below. */
var QUESTIONS = [

/* ============================ JAVA CORE ============================ */
{
  id: "java-1", category: "Java Core", difficulty: "medium",
  question: "How does HashMap work internally in Java?",
  answerEn: "<p>A <code class='inline'>HashMap</code> stores key-value pairs in an array of <b>buckets</b>. Steps:</p><ul><li>It calls <code class='inline'>hashCode()</code> on the key, then applies an internal hash spread, then <code class='inline'>index = hash &amp; (n-1)</code> to find the bucket.</li><li>If the bucket is empty, the entry goes in. If not, it's a <b>collision</b> — entries form a linked list.</li><li>Since Java 8, when a bucket's list length exceeds <b>8</b> (and capacity ≥ 64), it converts to a <b>balanced red-black tree</b>, improving worst-case lookup from O(n) to O(log n).</li><li>Default capacity is 16, load factor 0.75 — when size exceeds capacity×0.75 it <b>resizes</b> (doubles) and rehashes.</li></ul><p><b>Key point:</b> a correct <code class='inline'>equals()</code>/<code class='inline'>hashCode()</code> contract is mandatory, else keys get lost.</p>",
  answerHi: "<p><code class='inline'>HashMap</code> data ko <b>buckets</b> के array में रखता है (key-value pairs).</p><ul><li>पहले key का <code class='inline'>hashCode()</code> लेता है, फिर hashing करके bucket index निकालता है।</li><li>अगर bucket खाली है तो entry वहीं चली जाती है। अगर पहले से कुछ है तो <b>collision</b> होता है और linked list बन जाती है।</li><li>Java 8 से अगर एक bucket में 8 से ज़्यादा entries हो जाएँ (और capacity ≥ 64) तो वो <b>red-black tree</b> बन जाती है — जिससे lookup O(n) से O(log n) हो जाता है।</li><li>Default capacity 16, load factor 0.75 — जब entries इससे ज़्यादा हों तो map <b>resize</b> (double) होकर rehash करता है।</li></ul><p><b>याद रखें:</b> सही <code class='inline'>equals()</code> और <code class='inline'>hashCode()</code> होना ज़रूरी है, वरना keys खो सकती हैं।</p>"
},
{
  id: "java-2", category: "Java Core", difficulty: "medium",
  question: "Difference between HashMap, ConcurrentHashMap and synchronizedMap?",
  answerEn: "<ul><li><b>HashMap</b> — not thread-safe. Fast, but concurrent modification can corrupt it or throw <code class='inline'>ConcurrentModificationException</code>.</li><li><b>Collections.synchronizedMap</b> — wraps a map and locks the <b>entire map</b> on every operation. Thread-safe but poor concurrency (one lock).</li><li><b>ConcurrentHashMap</b> — thread-safe with much better throughput. It locks only a <b>segment/bucket</b> (bucket-level CAS + synchronized in Java 8), so multiple threads read/write different buckets in parallel. Never allows null keys/values.</li></ul><p>For multi-threaded services (like your payment backend) prefer <b>ConcurrentHashMap</b>.</p>",
  answerHi: "<ul><li><b>HashMap</b> — thread-safe नहीं है। तेज़ है पर एक साथ कई threads use करें तो data corrupt हो सकता है।</li><li><b>synchronizedMap</b> — पूरे map पर lock लगाता है, इसलिए thread-safe तो है पर slow (एक ही lock)।</li><li><b>ConcurrentHashMap</b> — thread-safe है और performance अच्छी है क्योंकि ये पूरे map की जगह सिर्फ़ <b>bucket-level</b> lock लगाता है। कई threads अलग-अलग buckets पर एक साथ काम कर सकते हैं। null key/value allow नहीं करता।</li></ul><p>Payment जैसे multi-threaded backend में <b>ConcurrentHashMap</b> ही best है।</p>"
},
{
  id: "java-3", category: "Java Core", difficulty: "medium",
  question: "Explain the equals() and hashCode() contract.",
  answerEn: "<p>The contract that ties them together:</p><ul><li>If two objects are <b>equal</b> (<code class='inline'>a.equals(b)</code> is true), they <b>must</b> return the same <code class='inline'>hashCode()</code>.</li><li>If two objects have the same hashCode, they are <b>not necessarily</b> equal (collisions are allowed).</li><li><code class='inline'>equals()</code> must be reflexive, symmetric, transitive, and consistent.</li></ul><p><b>Why it matters:</b> hash-based collections (HashMap/HashSet) first use hashCode to find the bucket, then equals to confirm. Override one without the other and lookups silently fail.</p>",
  answerHi: "<p>दोनों का आपस में contract:</p><ul><li>अगर दो objects <b>equal</b> हैं (<code class='inline'>a.equals(b)</code> true), तो उनका <code class='inline'>hashCode()</code> <b>ज़रूर</b> एक जैसा होना चाहिए।</li><li>अगर hashCode एक जैसा है तो objects equal हों — ये ज़रूरी नहीं (collision हो सकता है)।</li><li><code class='inline'>equals()</code> reflexive, symmetric, transitive और consistent होना चाहिए।</li></ul><p><b>क्यों ज़रूरी:</b> HashMap/HashSet पहले hashCode से bucket ढूँढते हैं फिर equals से confirm करते हैं। दोनों में से एक ही override करें तो lookup चुपचाप fail हो जाता है।</p>"
},
{
  id: "java-4", category: "Java Core", difficulty: "hard",
  question: "How do you handle concurrency in Java? (threads, executors, CompletableFuture)",
  answerEn: "<ul><li><b>Never create raw threads</b> in production — use an <code class='inline'>ExecutorService</code> thread pool (<code class='inline'>Executors.newFixedThreadPool</code>) so you control resource usage.</li><li><b>CompletableFuture</b> for async pipelines — chain with <code class='inline'>thenApply</code>, <code class='inline'>thenCompose</code>, combine with <code class='inline'>allOf</code>, handle errors with <code class='inline'>exceptionally</code>.</li><li><b>Synchronization:</b> <code class='inline'>synchronized</code> / <code class='inline'>ReentrantLock</code> for mutual exclusion; <code class='inline'>volatile</code> for visibility of a single flag; <code class='inline'>Atomic*</code> classes for lock-free counters.</li><li>Prefer <b>immutable objects</b> and concurrent collections to avoid shared mutable state altogether.</li></ul>",
  answerHi: "<ul><li>Production में <b>सीधे threads मत बनाओ</b> — <code class='inline'>ExecutorService</code> (thread pool) use करो ताकि resources control में रहें।</li><li>Async काम के लिए <b>CompletableFuture</b> — <code class='inline'>thenApply</code>, <code class='inline'>thenCompose</code>, <code class='inline'>allOf</code> से chain करो, errors के लिए <code class='inline'>exceptionally</code>।</li><li><b>Synchronization:</b> mutual exclusion के लिए <code class='inline'>synchronized</code>/<code class='inline'>ReentrantLock</code>; एक flag की visibility के लिए <code class='inline'>volatile</code>; counters के लिए <code class='inline'>Atomic</code> classes।</li><li>सबसे अच्छा — <b>immutable objects</b> और concurrent collections use करो ताकि shared mutable state ही न रहे।</li></ul>",
  code: "ExecutorService pool = Executors.newFixedThreadPool(10);\nCompletableFuture<Order> f = CompletableFuture\n    .supplyAsync(() -> fetchOrder(id), pool)\n    .thenApply(order -> enrich(order))\n    .exceptionally(ex -> fallbackOrder());"
},
{
  id: "java-5", category: "Java Core", difficulty: "medium",
  question: "What are Java 8 Streams and when should you use them?",
  answerEn: "<p>Streams provide a <b>declarative, functional</b> way to process collections — filter, map, reduce — without manual loops.</p><ul><li><b>Intermediate ops</b> (lazy): <code class='inline'>filter</code>, <code class='inline'>map</code>, <code class='inline'>sorted</code>.</li><li><b>Terminal ops</b> (trigger execution): <code class='inline'>collect</code>, <code class='inline'>forEach</code>, <code class='inline'>reduce</code>, <code class='inline'>count</code>.</li><li>Use <code class='inline'>parallelStream()</code> only for large, CPU-bound, stateless work.</li></ul><p><b>Caution:</b> streams are less readable for complex side effects and can be slower for tiny collections — a plain loop is fine there.</p>",
  answerHi: "<p>Streams collections को <b>functional तरीके</b> से process करते हैं — filter, map, reduce — बिना manual loop लिखे।</p><ul><li><b>Intermediate ops</b> (lazy): <code class='inline'>filter</code>, <code class='inline'>map</code>, <code class='inline'>sorted</code>।</li><li><b>Terminal ops</b> (execution शुरू): <code class='inline'>collect</code>, <code class='inline'>forEach</code>, <code class='inline'>reduce</code>।</li><li><code class='inline'>parallelStream()</code> सिर्फ़ बड़े, CPU-heavy, stateless काम के लिए।</li></ul><p><b>ध्यान:</b> complex side-effects में streams कम readable होते हैं और छोटी collections में slow — वहाँ simple loop ठीक है।</p>",
  code: "List<String> names = users.stream()\n    .filter(u -> u.isActive())\n    .map(User::getName)\n    .sorted()\n    .collect(Collectors.toList());"
},
{
  id: "java-6", category: "Java Core", difficulty: "hard",
  question: "Explain JVM memory model: heap, stack, and garbage collection.",
  answerEn: "<ul><li><b>Stack</b> — per-thread; holds method frames, local variables, references. Freed automatically when a method returns.</li><li><b>Heap</b> — shared; holds all objects. Divided into <b>Young Gen</b> (Eden + Survivor) and <b>Old Gen</b>.</li><li><b>GC:</b> new objects go to Eden. Minor GC clears short-lived objects; survivors are promoted to Old Gen. Major/Full GC cleans Old Gen (more expensive).</li><li><b>G1 GC</b> (default since Java 9) splits the heap into regions and targets predictable pause times.</li></ul><p><b>Memory leaks</b> in Java happen via lingering references (static collections, unclosed resources, listeners) — GC can't collect what's still reachable.</p>",
  answerHi: "<ul><li><b>Stack</b> — हर thread का अलग; method frames, local variables, references रखता है। Method खत्म होते ही free।</li><li><b>Heap</b> — shared; सारे objects यहाँ। <b>Young Gen</b> (Eden + Survivor) और <b>Old Gen</b> में बँटा है।</li><li><b>GC:</b> नए objects Eden में जाते हैं। Minor GC छोटी उम्र वाले objects हटाता है; बचे हुए Old Gen में promote होते हैं। Full GC Old Gen साफ़ करता है (महँगा)।</li><li><b>G1 GC</b> (Java 9+ default) heap को regions में बाँटकर predictable pause देता है।</li></ul><p><b>Memory leak</b> Java में तब होता है जब reference बचा रहे (static collections, unclosed resources) — जो reachable है उसे GC हटा नहीं सकता।</p>"
},
{
  id: "java-7", category: "Java Core", difficulty: "medium",
  question: "final vs finally vs finalize — and String vs StringBuilder?",
  answerEn: "<ul><li><b>final</b> — keyword: a final variable can't be reassigned, a final method can't be overridden, a final class can't be extended.</li><li><b>finally</b> — a block that always runs after try/catch (used to close resources).</li><li><b>finalize()</b> — a deprecated Object method called before GC; don't rely on it.</li></ul><p><b>String vs StringBuilder:</b> <code class='inline'>String</code> is immutable — every concatenation creates a new object. <code class='inline'>StringBuilder</code> is mutable and efficient for loops. <code class='inline'>StringBuffer</code> is the thread-safe (synchronized) version.</p>",
  answerHi: "<ul><li><b>final</b> — keyword: final variable दोबारा assign नहीं, final method override नहीं, final class extend नहीं।</li><li><b>finally</b> — block जो try/catch के बाद हमेशा चलता है (resources close करने के लिए)।</li><li><b>finalize()</b> — deprecated method जो GC से पहले चलता था; इस पर भरोसा मत करो।</li></ul><p><b>String vs StringBuilder:</b> <code class='inline'>String</code> immutable है — हर बार जोड़ने पर नया object बनता है। <code class='inline'>StringBuilder</code> mutable है, loops में efficient। <code class='inline'>StringBuffer</code> इसका thread-safe version है।</p>"
},

/* ============================ SPRING BOOT ============================ */
{
  id: "spring-1", category: "Spring Boot", difficulty: "easy",
  question: "What is Dependency Injection and IoC in Spring?",
  answerEn: "<p><b>Inversion of Control (IoC):</b> instead of a class creating its own dependencies, the Spring <b>container</b> creates and supplies them. Control is 'inverted' to the framework.</p><p><b>Dependency Injection (DI)</b> is how IoC is implemented — Spring injects beans via <b>constructor</b> (preferred), setter, or field.</p><p><b>Benefits:</b> loose coupling, easy testing (inject mocks), and single responsibility. Constructor injection is preferred because it makes dependencies explicit and supports immutability.</p>",
  answerHi: "<p><b>IoC (Inversion of Control):</b> class खुद अपनी dependencies बनाने की जगह, Spring <b>container</b> उन्हें बनाकर देता है। Control framework के पास चला जाता है।</p><p><b>DI (Dependency Injection)</b> IoC को implement करने का तरीका है — Spring beans को <b>constructor</b> (best), setter या field से inject करता है।</p><p><b>फायदे:</b> loose coupling, आसान testing (mocks inject कर सकते हैं)। Constructor injection best है क्योंकि dependencies साफ़ दिखती हैं और immutability मिलती है।</p>",
  code: "@Service\npublic class PaymentService {\n    private final GatewayClient client;\n    // constructor injection (no @Autowired needed for single ctor)\n    public PaymentService(GatewayClient client) {\n        this.client = client;\n    }\n}"
},
{
  id: "spring-2", category: "Spring Boot", difficulty: "medium",
  question: "How does Spring Boot auto-configuration work?",
  answerEn: "<p>Spring Boot auto-configures beans based on what's on the <b>classpath</b> and existing beans.</p><ul><li><code class='inline'>@SpringBootApplication</code> bundles <code class='inline'>@EnableAutoConfiguration</code>, <code class='inline'>@ComponentScan</code>, and <code class='inline'>@Configuration</code>.</li><li>Auto-config classes are listed in <code class='inline'>META-INF/spring.factories</code> (or the newer imports file).</li><li>They use <b>@Conditional</b> annotations — e.g. <code class='inline'>@ConditionalOnClass</code>, <code class='inline'>@ConditionalOnMissingBean</code> — so a bean is created only if it makes sense and you haven't defined your own.</li></ul><p>Example: add the JPA starter + an H2 dependency, and Spring auto-configures a DataSource, EntityManager, and transaction manager.</p>",
  answerHi: "<p>Spring Boot beans को <b>classpath</b> पर मौजूद libraries और existing beans के आधार पर अपने-आप configure करता है।</p><ul><li><code class='inline'>@SpringBootApplication</code> के अंदर <code class='inline'>@EnableAutoConfiguration</code>, <code class='inline'>@ComponentScan</code>, <code class='inline'>@Configuration</code> तीनों होते हैं।</li><li>Auto-config classes <code class='inline'>spring.factories</code> में listed होती हैं।</li><li>ये <b>@Conditional</b> annotations use करती हैं — जैसे <code class='inline'>@ConditionalOnClass</code>, <code class='inline'>@ConditionalOnMissingBean</code> — यानी bean तभी बनेगा जब ज़रूरी हो और आपने खुद न बनाया हो।</li></ul><p>जैसे JPA starter + H2 add करते ही Spring DataSource, EntityManager अपने-आप बना देता है।</p>"
},
{
  id: "spring-3", category: "Spring Boot", difficulty: "medium",
  question: "Explain @Transactional — propagation and isolation.",
  answerEn: "<p><code class='inline'>@Transactional</code> wraps a method in a database transaction — commit on success, rollback on a runtime exception.</p><ul><li><b>Propagation</b> — how transactions nest: <code class='inline'>REQUIRED</code> (default, join existing or create), <code class='inline'>REQUIRES_NEW</code> (suspend outer, start fresh), <code class='inline'>NESTED</code>, <code class='inline'>MANDATORY</code>.</li><li><b>Isolation</b> — visibility of uncommitted data: <code class='inline'>READ_COMMITTED</code> (default in most DBs), <code class='inline'>REPEATABLE_READ</code>, <code class='inline'>SERIALIZABLE</code>. Higher isolation = fewer anomalies but less concurrency.</li></ul><p><b>Gotchas:</b> by default it only rolls back on unchecked exceptions (use <code class='inline'>rollbackFor</code> for checked); and it works via proxies, so <b>self-invocation</b> (calling a @Transactional method from the same class) is not intercepted.</p>",
  answerHi: "<p><code class='inline'>@Transactional</code> method को database transaction में लपेटता है — success पर commit, runtime exception पर rollback।</p><ul><li><b>Propagation</b> — transactions कैसे nest हों: <code class='inline'>REQUIRED</code> (default), <code class='inline'>REQUIRES_NEW</code> (नया transaction), <code class='inline'>NESTED</code>, <code class='inline'>MANDATORY</code>।</li><li><b>Isolation</b> — uncommitted data कितना दिखे: <code class='inline'>READ_COMMITTED</code> (ज़्यादातर DB में default), <code class='inline'>REPEATABLE_READ</code>, <code class='inline'>SERIALIZABLE</code>। ज़्यादा isolation = कम anomalies पर कम concurrency।</li></ul><p><b>ध्यान:</b> default में सिर्फ़ unchecked exceptions पर rollback होता है (checked के लिए <code class='inline'>rollbackFor</code>); और ये proxy से काम करता है इसलिए <b>same class के अंदर</b> से call करने पर intercept नहीं होता।</p>"
},
{
  id: "spring-4", category: "Spring Boot", difficulty: "medium",
  question: "Bean scopes and bean lifecycle in Spring?",
  answerEn: "<p><b>Scopes:</b> <code class='inline'>singleton</code> (default, one per container), <code class='inline'>prototype</code> (new each request), and web scopes <code class='inline'>request</code>, <code class='inline'>session</code>, <code class='inline'>application</code>.</p><p><b>Lifecycle:</b> instantiate → populate dependencies → <code class='inline'>@PostConstruct</code> / <code class='inline'>InitializingBean</code> → bean is ready and in use → <code class='inline'>@PreDestroy</code> / <code class='inline'>DisposableBean</code> on shutdown.</p><p>Note: singleton beans holding mutable state are a common bug source in concurrent apps — keep them stateless.</p>",
  answerHi: "<p><b>Scopes:</b> <code class='inline'>singleton</code> (default, container में एक), <code class='inline'>prototype</code> (हर बार नया), और web scopes <code class='inline'>request</code>, <code class='inline'>session</code>, <code class='inline'>application</code>।</p><p><b>Lifecycle:</b> object बनना → dependencies भरना → <code class='inline'>@PostConstruct</code> → bean ready और use में → shutdown पर <code class='inline'>@PreDestroy</code>।</p><p>ध्यान: singleton bean में mutable state रखना concurrent apps में common bug है — इन्हें stateless रखो।</p>"
},
{
  id: "spring-5", category: "Spring Boot", difficulty: "medium",
  question: "How do you handle exceptions globally in a Spring Boot REST API?",
  answerEn: "<p>Use a centralized handler with <code class='inline'>@RestControllerAdvice</code> and <code class='inline'>@ExceptionHandler</code> methods. This keeps controllers clean and returns consistent error responses (status code + body).</p><ul><li>Map domain exceptions to proper HTTP codes (404 not found, 400 validation, 409 conflict).</li><li>Combine with bean validation (<code class='inline'>@Valid</code>) to catch <code class='inline'>MethodArgumentNotValidException</code>.</li><li>Return a structured error object (timestamp, message, path) — never leak stack traces to clients.</li></ul>",
  answerHi: "<p>एक central handler बनाओ — <code class='inline'>@RestControllerAdvice</code> + <code class='inline'>@ExceptionHandler</code> methods से। इससे controllers साफ़ रहते हैं और सभी errors का response एक जैसा (status + body) मिलता है।</p><ul><li>Domain exceptions को सही HTTP code से map करो (404, 400, 409)।</li><li><code class='inline'>@Valid</code> validation के साथ जोड़ो ताकि <code class='inline'>MethodArgumentNotValidException</code> पकड़ में आए।</li><li>Structured error object लौटाओ (timestamp, message, path) — client को कभी stack trace मत दिखाओ।</li></ul>",
  code: "@RestControllerAdvice\npublic class ApiExceptionHandler {\n    @ExceptionHandler(ResourceNotFoundException.class)\n    public ResponseEntity<ApiError> handle(ResourceNotFoundException ex) {\n        return ResponseEntity.status(HttpStatus.NOT_FOUND)\n            .body(new ApiError(ex.getMessage()));\n    }\n}"
},
{
  id: "spring-6", category: "Spring Boot", difficulty: "hard",
  question: "What is the N+1 query problem in Hibernate and how do you fix it?",
  answerEn: "<p>The <b>N+1 problem</b>: you fetch N parent rows with 1 query, then Hibernate fires 1 extra query per parent to load its lazy association — N+1 total queries. It silently kills performance.</p><p><b>Fixes:</b></p><ul><li><b>JOIN FETCH</b> in JPQL to load parents + children in one query.</li><li><b>@EntityGraph</b> to declaratively fetch associations.</li><li><b>Batch fetching</b> (<code class='inline'>@BatchSize</code>) to load children in groups instead of one-by-one.</li><li>Use <b>DTO projections</b> when you only need a few fields.</li></ul>",
  answerHi: "<p><b>N+1 problem:</b> आप 1 query से N parent rows लाते हैं, फिर Hibernate हर parent के lazy association के लिए 1-1 extra query चलाता है — कुल N+1 queries। ये चुपचाप performance खा जाता है।</p><p><b>Fix:</b></p><ul><li>JPQL में <b>JOIN FETCH</b> — parent + children एक ही query में।</li><li><b>@EntityGraph</b> से associations fetch करना।</li><li><b>@BatchSize</b> से children groups में लाना।</li><li>सिर्फ़ कुछ fields चाहिए तो <b>DTO projection</b> use करो।</li></ul>",
  code: "@Query(\"SELECT o FROM Order o JOIN FETCH o.items WHERE o.userId = :id\")\nList<Order> findWithItems(@Param(\"id\") Long id);"
},
{
  id: "spring-7", category: "Spring Boot", difficulty: "medium",
  question: "How do you secure a REST API with JWT?",
  answerEn: "<p>JWT (JSON Web Token) enables <b>stateless</b> authentication — no server-side session.</p><ul><li>On login, verify credentials and issue a signed JWT (header.payload.signature) with claims (userId, roles, expiry).</li><li>Client sends it in <code class='inline'>Authorization: Bearer &lt;token&gt;</code> on each request.</li><li>A Spring Security filter validates the signature and expiry, then sets the <code class='inline'>SecurityContext</code>.</li><li>Use short-lived access tokens + refresh tokens; sign with a strong secret or RSA key; never store sensitive data in the payload (it's only base64, not encrypted).</li></ul>",
  answerHi: "<p>JWT से <b>stateless</b> authentication होती है — server पर session रखने की ज़रूरत नहीं।</p><ul><li>Login पर credentials verify करके एक signed JWT देते हैं जिसमें claims होती हैं (userId, roles, expiry)।</li><li>Client हर request में <code class='inline'>Authorization: Bearer &lt;token&gt;</code> भेजता है।</li><li>Spring Security filter signature और expiry check करके <code class='inline'>SecurityContext</code> set करता है।</li><li>Short access token + refresh token रखो; strong secret/RSA से sign करो; payload में sensitive data मत रखो (ये सिर्फ़ base64 है, encrypted नहीं)।</li></ul>"
},

/* ============================ MICROSERVICES ============================ */
{
  id: "micro-1", category: "Microservices", difficulty: "medium",
  question: "Monolith vs Microservices — trade-offs?",
  answerEn: "<p><b>Monolith:</b> one deployable. Simpler to build, test, and deploy early on; but scaling, releasing, and team autonomy get hard as it grows.</p><p><b>Microservices:</b> independently deployable services, each owning its data.</p><ul><li><b>Pros:</b> independent scaling & deployment, tech freedom per service, fault isolation, team ownership.</li><li><b>Cons:</b> distributed-system complexity — network latency, eventual consistency, harder debugging/tracing, ops overhead.</li></ul><p><b>Rule of thumb:</b> start monolith, split into microservices when clear domain boundaries and scaling pain appear. Don't adopt microservices for a small team/product.</p>",
  answerHi: "<p><b>Monolith:</b> एक ही deployable app। शुरू में बनाना, test, deploy आसान; पर बड़ा होने पर scaling और release मुश्किल।</p><p><b>Microservices:</b> अलग-अलग deploy होने वाली services, हर एक का अपना data।</p><ul><li><b>फायदे:</b> independent scaling/deployment, हर service की अपनी tech, fault isolation, team ownership।</li><li><b>नुकसान:</b> distributed system की complexity — network latency, eventual consistency, debugging मुश्किल, ops overhead।</li></ul><p><b>नियम:</b> monolith से शुरू करो, domain boundaries और scaling की दिक्कत आने पर microservices में बाँटो। छोटे product/team के लिए microservices ज़रूरी नहीं।</p>"
},
{
  id: "micro-2", category: "Microservices", difficulty: "hard",
  question: "How do you keep data consistent across microservices? (Saga pattern)",
  answerEn: "<p>You can't use one distributed ACID transaction across services. Instead use the <b>Saga pattern</b> — a sequence of local transactions, each publishing an event that triggers the next step; if a step fails, run <b>compensating transactions</b> to undo prior steps.</p><ul><li><b>Choreography:</b> services react to each other's events (no central coordinator) — simple but harder to trace.</li><li><b>Orchestration:</b> a central orchestrator tells each service what to do — easier to reason about and monitor.</li></ul><p>Combine with <b>idempotency</b> (safe retries) and the <b>outbox pattern</b> (atomically save state + event) — critical in payments to avoid double charges.</p>",
  answerHi: "<p>Services के बीच एक distributed ACID transaction नहीं हो सकता। इसकी जगह <b>Saga pattern</b> use करते हैं — कई local transactions की एक chain, हर step event publish करके अगले को trigger करता है; कोई step fail हो तो <b>compensating transaction</b> से पिछले steps undo करते हैं।</p><ul><li><b>Choreography:</b> services एक-दूसरे के events पर react करती हैं (कोई central coordinator नहीं) — simple पर trace करना मुश्किल।</li><li><b>Orchestration:</b> एक central orchestrator हर service को बताता है क्या करना है — monitor करना आसान।</li></ul><p>इसे <b>idempotency</b> (safe retries) और <b>outbox pattern</b> के साथ जोड़ो — payments में double charge रोकने के लिए ज़रूरी।</p>"
},
{
  id: "micro-3", category: "Microservices", difficulty: "medium",
  question: "What is a Circuit Breaker and why use it?",
  answerEn: "<p>A <b>circuit breaker</b> (e.g. Resilience4j) prevents cascading failures. If a downstream service keeps failing, the breaker <b>opens</b> and fails fast (returns a fallback) instead of piling up blocked threads.</p><ul><li><b>Closed</b> — calls pass through normally.</li><li><b>Open</b> — after a failure threshold, calls short-circuit immediately.</li><li><b>Half-open</b> — after a wait, a few trial calls test if the service recovered.</li></ul><p>Pair with <b>timeouts</b>, <b>retries</b> (with backoff), and <b>bulkheads</b> to isolate failures.</p>",
  answerHi: "<p><b>Circuit breaker</b> (जैसे Resilience4j) cascading failures रोकता है। अगर कोई downstream service बार-बार fail हो रही है तो breaker <b>open</b> होकर तुरंत fail (fallback देकर) कर देता है, threads block नहीं होते।</p><ul><li><b>Closed</b> — calls normal चलती हैं।</li><li><b>Open</b> — failure threshold के बाद calls तुरंत fail।</li><li><b>Half-open</b> — कुछ देर बाद थोड़ी calls चलाकर देखते हैं service ठीक हुई या नहीं।</li></ul><p>इसके साथ <b>timeouts</b>, <b>retries</b> (backoff के साथ) और <b>bulkhead</b> भी use करो।</p>"
},
{
  id: "micro-4", category: "Microservices", difficulty: "medium",
  question: "Sync (REST) vs Async (messaging) communication — when to use which?",
  answerEn: "<p><b>Synchronous (REST/gRPC):</b> caller waits for a response. Use when you need an immediate result (e.g. validate a payment). Downside: tight coupling — if the callee is down/slow, the caller suffers.</p><p><b>Asynchronous (RabbitMQ/Kafka):</b> caller publishes a message and moves on. Use for decoupling, load leveling, and events that don't need an instant reply (email, notifications, order processing). Gives resilience and buffering but adds eventual consistency.</p><p><b>Common design:</b> sync for the request path, async (events) for side-effects.</p>",
  answerHi: "<p><b>Synchronous (REST/gRPC):</b> caller response का इंतज़ार करता है। जब तुरंत result चाहिए तब use करो (जैसे payment validate)। नुकसान: tight coupling — callee down/slow हो तो caller भी अटकता है।</p><p><b>Asynchronous (RabbitMQ/Kafka):</b> caller message डालकर आगे बढ़ जाता है। Decoupling, load leveling और ऐसे events के लिए जहाँ तुरंत reply ज़रूरी नहीं (email, notification, order processing)। Resilience मिलती है पर eventual consistency आती है।</p><p><b>आम design:</b> request path के लिए sync, side-effects के लिए async events।</p>"
},
{
  id: "micro-5", category: "Microservices", difficulty: "medium",
  question: "How do you handle service discovery, config, and an API gateway?",
  answerEn: "<ul><li><b>API Gateway</b> (e.g. Spring Cloud Gateway) — single entry point handling routing, auth, rate limiting, and SSL termination, so clients don't call services directly.</li><li><b>Service Discovery</b> (Eureka/Consul or Kubernetes DNS) — services register themselves; callers look them up by name instead of hardcoding IPs (which change as instances scale).</li><li><b>Config Server</b> — centralized, environment-specific config so you don't rebuild to change a value; supports refresh without redeploy.</li></ul>",
  answerHi: "<ul><li><b>API Gateway</b> (जैसे Spring Cloud Gateway) — single entry point जो routing, auth, rate limiting, SSL संभालता है, ताकि clients सीधे services को call न करें।</li><li><b>Service Discovery</b> (Eureka/Consul या Kubernetes DNS) — services खुद को register करती हैं; caller उन्हें name से ढूँढता है, hardcoded IP नहीं (instances scale होने पर IP बदलती है)।</li><li><b>Config Server</b> — centralized environment-wise config, ताकि value बदलने के लिए दोबारा build न करना पड़े।</li></ul>"
},
{
  id: "micro-6", category: "Microservices", difficulty: "hard",
  question: "What is idempotency and why is it critical for payments?",
  answerEn: "<p>An <b>idempotent</b> operation produces the same result whether it runs once or many times. In distributed systems, retries and duplicate messages are inevitable — without idempotency you could <b>charge a card twice</b>.</p><p><b>How to implement:</b></p><ul><li>Client sends a unique <b>idempotency key</b> per request.</li><li>Server stores processed keys; a repeat key returns the original result instead of re-processing.</li><li>Make message consumers idempotent (check if the event was already applied).</li></ul><p>This is exactly why payment APIs (Stripe, and your Bancstac work) require idempotency keys.</p>",
  answerHi: "<p><b>Idempotent</b> operation एक बार चले या कई बार, result वही रहता है। Distributed systems में retries और duplicate messages होना तय है — idempotency न हो तो <b>card दो बार charge</b> हो सकता है।</p><p><b>कैसे करें:</b></p><ul><li>Client हर request के लिए unique <b>idempotency key</b> भेजे।</li><li>Server processed keys store करे; वही key दोबारा आए तो original result लौटाए, दोबारा process न करे।</li><li>Message consumers को idempotent बनाओ (check करो event पहले apply हुआ या नहीं)।</li></ul><p>इसीलिए payment APIs (Stripe, आपका Bancstac) idempotency key माँगते हैं।</p>"
},

/* ============================ RABBITMQ ============================ */
{
  id: "rmq-1", category: "RabbitMQ & Messaging", difficulty: "medium",
  question: "Explain RabbitMQ core concepts: exchange, queue, binding, routing key.",
  answerEn: "<p>RabbitMQ decouples producers from consumers:</p><ul><li><b>Producer</b> publishes a message to an <b>Exchange</b> (not directly to a queue).</li><li><b>Exchange</b> routes it to <b>Queues</b> based on the <b>routing key</b> and <b>bindings</b>.</li><li><b>Queue</b> buffers messages until a <b>Consumer</b> acknowledges them.</li></ul><p><b>Exchange types:</b> <code class='inline'>direct</code> (exact routing-key match), <code class='inline'>topic</code> (wildcard patterns like <code class='inline'>order.*</code>), <code class='inline'>fanout</code> (broadcast to all bound queues), <code class='inline'>headers</code>.</p>",
  answerHi: "<p>RabbitMQ producer और consumer को अलग करता है:</p><ul><li><b>Producer</b> message को <b>Exchange</b> पर भेजता है (सीधे queue पर नहीं)।</li><li><b>Exchange</b> उसे <b>routing key</b> और <b>bindings</b> के हिसाब से <b>Queues</b> तक पहुँचाता है।</li><li><b>Queue</b> messages को तब तक रखता है जब तक <b>Consumer</b> acknowledge न कर दे।</li></ul><p><b>Exchange types:</b> <code class='inline'>direct</code> (exact match), <code class='inline'>topic</code> (wildcard जैसे <code class='inline'>order.*</code>), <code class='inline'>fanout</code> (सबको broadcast), <code class='inline'>headers</code>।</p>"
},
{
  id: "rmq-2", category: "RabbitMQ & Messaging", difficulty: "medium",
  question: "How do you guarantee message delivery and handle failures in RabbitMQ?",
  answerEn: "<ul><li><b>Acknowledgements:</b> consumer sends <code class='inline'>ack</code> only after successful processing; if it crashes, the unacked message is redelivered (at-least-once delivery).</li><li><b>Publisher confirms:</b> broker confirms it persisted the message.</li><li><b>Durable queues + persistent messages</b> survive broker restarts.</li><li><b>Dead Letter Queue (DLQ):</b> messages that fail repeatedly (or are rejected/expired) are routed to a DLQ for inspection instead of being lost or retried forever.</li><li>Because delivery is at-least-once, make consumers <b>idempotent</b>.</li></ul>",
  answerHi: "<ul><li><b>Acknowledgement:</b> consumer successful processing के बाद ही <code class='inline'>ack</code> भेजे; crash हो जाए तो unacked message दोबारा deliver होता है (at-least-once)।</li><li><b>Publisher confirms:</b> broker confirm करता है कि message save हो गया।</li><li><b>Durable queue + persistent messages</b> broker restart पर भी बचे रहते हैं।</li><li><b>Dead Letter Queue (DLQ):</b> बार-बार fail होने वाले messages DLQ में जाते हैं, ताकि खोएँ नहीं और हमेशा retry भी न हों।</li><li>Delivery at-least-once है, इसलिए consumers को <b>idempotent</b> बनाओ।</li></ul>"
},
{
  id: "rmq-3", category: "RabbitMQ & Messaging", difficulty: "medium",
  question: "RabbitMQ vs Kafka — when would you choose each?",
  answerEn: "<p><b>RabbitMQ</b> — a traditional message broker (smart broker, dumb consumer). Great for <b>task queues</b>, complex routing, request/reply, and per-message acknowledgement. Messages are removed once consumed.</p><p><b>Kafka</b> — a distributed <b>log</b>. Great for high-throughput event streaming, replaying events, and multiple consumer groups reading the same stream. Messages are retained for a configured period.</p><p><b>Choose RabbitMQ</b> for command/task distribution and routing flexibility; <b>choose Kafka</b> for event sourcing, analytics pipelines, and massive throughput.</p>",
  answerHi: "<p><b>RabbitMQ</b> — traditional message broker। <b>Task queues</b>, complex routing, request/reply और per-message ack के लिए बढ़िया। Message consume होते ही हट जाता है।</p><p><b>Kafka</b> — distributed <b>log</b>। High-throughput event streaming, events को replay करने और कई consumer groups के लिए बढ़िया। Messages कुछ समय तक store रहते हैं।</p><p><b>RabbitMQ चुनो</b> task distribution और routing के लिए; <b>Kafka चुनो</b> event sourcing, analytics और बहुत बड़े throughput के लिए।</p>"
},

/* ============================ DATABASES ============================ */
{
  id: "db-1", category: "Databases & SQL", difficulty: "medium",
  question: "What are database indexes and what are their trade-offs?",
  answerEn: "<p>An <b>index</b> is a data structure (usually a B-tree) that lets the DB find rows without scanning the whole table — like a book's index.</p><ul><li><b>Speeds up</b> reads on <code class='inline'>WHERE</code>, <code class='inline'>JOIN</code>, <code class='inline'>ORDER BY</code> columns.</li><li><b>Costs:</b> extra storage and slower writes (every insert/update must maintain the index).</li><li><b>Composite index</b> order matters — it helps queries that filter on a <b>left-most prefix</b> of the columns.</li></ul><p>Use <code class='inline'>EXPLAIN</code> to verify a query actually uses your index.</p>",
  answerHi: "<p><b>Index</b> एक data structure (आमतौर पर B-tree) है जो DB को पूरी table scan किए बिना rows ढूँढने देता है — किताब के index की तरह।</p><ul><li><code class='inline'>WHERE</code>, <code class='inline'>JOIN</code>, <code class='inline'>ORDER BY</code> वाले columns पर reads <b>तेज़</b> करता है।</li><li><b>कीमत:</b> extra storage और writes slow (हर insert/update पर index update होता है)।</li><li><b>Composite index</b> में column order मायने रखता है — ये <b>left-most prefix</b> वाली queries में मदद करता है।</li></ul><p><code class='inline'>EXPLAIN</code> से check करो कि query सच में index use कर रही है या नहीं।</p>"
},
{
  id: "db-2", category: "Databases & SQL", difficulty: "medium",
  question: "Explain ACID properties and transaction isolation levels.",
  answerEn: "<p><b>ACID:</b></p><ul><li><b>Atomicity</b> — all steps commit or none do.</li><li><b>Consistency</b> — the DB moves from one valid state to another.</li><li><b>Isolation</b> — concurrent transactions don't corrupt each other.</li><li><b>Durability</b> — committed data survives crashes.</li></ul><p><b>Isolation levels</b> (weak → strong) trade concurrency for correctness: <code class='inline'>READ UNCOMMITTED</code> (dirty reads), <code class='inline'>READ COMMITTED</code>, <code class='inline'>REPEATABLE READ</code> (prevents non-repeatable reads), <code class='inline'>SERIALIZABLE</code> (full isolation, prevents phantom reads).</p>",
  answerHi: "<p><b>ACID:</b></p><ul><li><b>Atomicity</b> — या तो सारे steps commit हों या कोई नहीं।</li><li><b>Consistency</b> — DB एक valid state से दूसरे valid state में जाए।</li><li><b>Isolation</b> — एक साथ चलने वाले transactions एक-दूसरे को corrupt न करें।</li><li><b>Durability</b> — commit हुआ data crash में भी बचे।</li></ul><p><b>Isolation levels</b> (weak → strong): <code class='inline'>READ UNCOMMITTED</code> (dirty read), <code class='inline'>READ COMMITTED</code>, <code class='inline'>REPEATABLE READ</code>, <code class='inline'>SERIALIZABLE</code> (पूरा isolation)। जितना strong उतना correct पर कम concurrency।</p>"
},
{
  id: "db-3", category: "Databases & SQL", difficulty: "medium",
  question: "SQL vs NoSQL — how do you decide?",
  answerEn: "<p><b>SQL (MySQL/PostgreSQL):</b> structured schema, strong consistency, ACID transactions, powerful joins. Best for financial/transactional data where correctness matters (your payments work).</p><p><b>NoSQL (MongoDB/Redis/Elasticsearch):</b> flexible schema, horizontal scale, high throughput.</p><ul><li><b>Document (Mongo)</b> — flexible/evolving data.</li><li><b>Key-value (Redis)</b> — caching, sessions.</li><li><b>Search (Elasticsearch)</b> — full-text search, log analytics.</li></ul><p>Real systems are <b>polyglot</b> — MySQL for orders, Redis for cache, Elasticsearch for search (as in your resume).</p>",
  answerHi: "<p><b>SQL (MySQL/PostgreSQL):</b> fixed schema, strong consistency, ACID transactions, powerful joins। Financial/transactional data के लिए best जहाँ correctness ज़रूरी है (आपका payments काम)।</p><p><b>NoSQL (MongoDB/Redis/Elasticsearch):</b> flexible schema, horizontal scale, high throughput।</p><ul><li><b>Document (Mongo)</b> — बदलता हुआ data।</li><li><b>Key-value (Redis)</b> — caching, sessions।</li><li><b>Search (Elasticsearch)</b> — full-text search, logs।</li></ul><p>असली systems <b>polyglot</b> होते हैं — orders के लिए MySQL, cache के लिए Redis, search के लिए Elasticsearch।</p>"
},
{
  id: "db-4", category: "Databases & SQL", difficulty: "easy",
  question: "Explain the different types of SQL JOINs.",
  answerEn: "<ul><li><b>INNER JOIN</b> — only rows matching in both tables.</li><li><b>LEFT JOIN</b> — all rows from the left table + matches from the right (NULLs where no match).</li><li><b>RIGHT JOIN</b> — all rows from the right + matches from the left.</li><li><b>FULL OUTER JOIN</b> — all rows from both, matched where possible.</li><li><b>CROSS JOIN</b> — Cartesian product (every combination).</li></ul>",
  answerHi: "<ul><li><b>INNER JOIN</b> — सिर्फ़ वो rows जो दोनों tables में match करें।</li><li><b>LEFT JOIN</b> — left table की सारी rows + right के matches (match न हो तो NULL)।</li><li><b>RIGHT JOIN</b> — right की सारी rows + left के matches।</li><li><b>FULL OUTER JOIN</b> — दोनों tables की सारी rows।</li><li><b>CROSS JOIN</b> — हर combination (Cartesian product)।</li></ul>",
  code: "SELECT o.id, u.name\nFROM orders o\nLEFT JOIN users u ON o.user_id = u.id;"
},

/* ============================ REACT ============================ */
{
  id: "react-1", category: "React & TypeScript", difficulty: "medium",
  question: "Explain useEffect — dependencies, cleanup, and common mistakes.",
  answerEn: "<p><code class='inline'>useEffect</code> runs side effects (data fetching, subscriptions, timers) after render.</p><ul><li><b>Dependency array</b> controls when it re-runs: <code class='inline'>[]</code> = once on mount; <code class='inline'>[a, b]</code> = when a or b changes; omitted = every render.</li><li><b>Cleanup function</b> (the returned function) runs before the next effect and on unmount — use it to clear timers/subscriptions to avoid leaks.</li></ul><p><b>Common mistakes:</b> missing dependencies (stale values), causing infinite loops by setting state without proper deps, and forgetting cleanup.</p>",
  answerHi: "<p><code class='inline'>useEffect</code> render के बाद side effects चलाता है (data fetch, subscription, timer)।</p><ul><li><b>Dependency array</b> तय करती है कब दोबारा चले: <code class='inline'>[]</code> = सिर्फ़ mount पर; <code class='inline'>[a,b]</code> = a या b बदलने पर; न दें तो हर render पर।</li><li><b>Cleanup function</b> (return की गई function) अगले effect से पहले और unmount पर चलती है — timers/subscriptions clear करने के लिए, leaks रोकने के लिए।</li></ul><p><b>आम गलतियाँ:</b> dependency छूट जाना (stale value), गलत deps से infinite loop, cleanup भूल जाना।</p>",
  code: "useEffect(() => {\n  const id = setInterval(tick, 1000);\n  return () => clearInterval(id); // cleanup\n}, []);"
},
{
  id: "react-2", category: "React & TypeScript", difficulty: "medium",
  question: "What causes unnecessary re-renders and how do you optimize?",
  answerEn: "<p>A component re-renders when its <b>state/props change</b> or its <b>parent re-renders</b>. Excess re-renders hurt performance.</p><ul><li><b>React.memo</b> — skips re-render if props are unchanged (shallow compare).</li><li><b>useMemo</b> — memoizes an expensive computed value.</li><li><b>useCallback</b> — memoizes a function so child props stay stable.</li><li>Give lists stable <b>keys</b> (not array index for dynamic lists).</li><li>Don't create new objects/arrays inline in props unnecessarily.</li></ul><p><b>Caution:</b> don't over-optimize — memoization has its own cost; profile first.</p>",
  answerHi: "<p>Component तब re-render होता है जब उसका <b>state/props बदले</b> या <b>parent re-render</b> हो। ज़्यादा re-render performance खराब करते हैं।</p><ul><li><b>React.memo</b> — props न बदलें तो re-render skip।</li><li><b>useMemo</b> — महँगी calculation memoize करता है।</li><li><b>useCallback</b> — function memoize करता है ताकि child के props stable रहें।</li><li>Lists को stable <b>key</b> दो (dynamic list में array index मत use करो)।</li></ul><p><b>ध्यान:</b> ज़रूरत से ज़्यादा optimize मत करो — memoization की भी cost है; पहले profile करो।</p>"
},
{
  id: "react-3", category: "React & TypeScript", difficulty: "medium",
  question: "What is React Remix and how do loaders/actions work?",
  answerEn: "<p><b>Remix</b> is a full-stack React framework focused on web fundamentals and SSR.</p><ul><li><b>Loaders</b> — server functions that fetch data <b>before</b> a route renders; the component reads it via <code class='inline'>useLoaderData()</code>. This avoids client-side loading spinners and waterfalls.</li><li><b>Actions</b> — server functions that handle form submissions (POST/PUT/DELETE); Remix uses native <code class='inline'>&lt;Form&gt;</code> so it works even without JS (progressive enhancement).</li><li>Nested routes let each layout segment load its own data in parallel.</li></ul><p>Result: fast, SEO-friendly pages with less client state management.</p>",
  answerHi: "<p><b>Remix</b> एक full-stack React framework है जो web fundamentals और SSR पर focus करता है।</p><ul><li><b>Loaders</b> — server functions जो route render होने से <b>पहले</b> data ले आती हैं; component <code class='inline'>useLoaderData()</code> से पढ़ता है। इससे loading spinners और waterfalls कम होते हैं।</li><li><b>Actions</b> — server functions जो form submit (POST/PUT/DELETE) संभालती हैं; Remix native <code class='inline'>&lt;Form&gt;</code> use करता है इसलिए JS के बिना भी चलता है।</li><li>Nested routes में हर layout अपना data parallel में load करता है।</li></ul><p>नतीजा: तेज़, SEO-friendly pages और कम client state।</p>"
},
{
  id: "react-4", category: "React & TypeScript", difficulty: "easy",
  question: "TypeScript: interface vs type, and why use generics?",
  answerEn: "<p><b>interface vs type:</b> both describe object shapes. <code class='inline'>interface</code> can be re-opened/merged and extended — good for public object contracts. <code class='inline'>type</code> is more flexible — unions, intersections, primitives, tuples.</p><p><b>Generics</b> let you write reusable, type-safe code that works over many types without losing type information.</p>",
  answerHi: "<p><b>interface vs type:</b> दोनों object की shape बताते हैं। <code class='inline'>interface</code> दोबारा extend/merge हो सकता है — public contracts के लिए अच्छा। <code class='inline'>type</code> ज़्यादा flexible है — unions, intersections, primitives, tuples।</p><p><b>Generics</b> से reusable, type-safe code लिखते हैं जो कई types पर चले और type info भी न खोए।</p>",
  code: "function first<T>(arr: T[]): T | undefined {\n  return arr[0];\n}\nconst n = first<number>([1, 2, 3]); // n: number | undefined"
},

/* ============================ SYSTEM DESIGN ============================ */
{
  id: "sd-1", category: "System Design", difficulty: "hard",
  question: "Design a payment gateway — how would you approach it?",
  answerEn: "<p>Structure the answer: requirements → API → data → flow → scale.</p><ul><li><b>Requirements:</b> accept payments across card networks, high availability, idempotency, PCI DSS, 3DS auth, audit trail.</li><li><b>Flow:</b> API gateway → payment service creates a transaction (status PENDING) → calls the card network/acquirer → 3DS challenge if needed → update status → publish an event.</li><li><b>Reliability:</b> idempotency keys to avoid double charges, outbox pattern for atomic event publishing, retries with backoff, circuit breakers on external calls.</li><li><b>Data:</b> MySQL for transactions (ACID), Redis for caching/rate limiting, message queue for async settlement/notifications.</li><li><b>Security:</b> never store raw PAN — tokenize; encrypt at rest and in transit; strict access control and audit logs.</li></ul><p>This mirrors your Bancstac experience — lead with that.</p>",
  answerHi: "<p>जवाब का structure: requirements → API → data → flow → scale।</p><ul><li><b>Requirements:</b> कई card networks, high availability, idempotency, PCI DSS, 3DS auth, audit trail।</li><li><b>Flow:</b> API gateway → payment service transaction बनाए (status PENDING) → card network को call → ज़रूरत हो तो 3DS challenge → status update → event publish।</li><li><b>Reliability:</b> double charge रोकने के लिए idempotency keys, atomic event के लिए outbox pattern, backoff के साथ retries, external calls पर circuit breaker।</li><li><b>Data:</b> transactions के लिए MySQL (ACID), caching/rate-limit के लिए Redis, async settlement के लिए queue।</li><li><b>Security:</b> raw card number कभी store न करो — tokenize करो; data encrypt करो; strict access control और audit logs।</li></ul><p>ये आपके Bancstac अनुभव से मेल खाता है — इसी से शुरू करो।</p>"
},
{
  id: "sd-2", category: "System Design", difficulty: "medium",
  question: "How would you design a rate limiter?",
  answerEn: "<p><b>Goal:</b> limit requests per client (e.g. 100/min) to protect services.</p><p><b>Algorithms:</b></p><ul><li><b>Token bucket</b> — tokens refill at a fixed rate; each request consumes one; allows short bursts. Most common.</li><li><b>Sliding window</b> — smoother, more accurate than fixed windows.</li><li><b>Fixed window counter</b> — simple but allows bursts at window edges.</li></ul><p><b>Implementation:</b> store counters in <b>Redis</b> (fast, shared across instances, atomic <code class='inline'>INCR</code> + TTL). Apply at the API gateway. Return HTTP <b>429</b> with a <code class='inline'>Retry-After</code> header when exceeded.</p>",
  answerHi: "<p><b>लक्ष्य:</b> हर client की requests limit करना (जैसे 100/min) ताकि services safe रहें।</p><p><b>Algorithms:</b></p><ul><li><b>Token bucket</b> — tokens fixed rate पर भरते हैं; हर request एक token लेती है; थोड़ा burst allow। सबसे common।</li><li><b>Sliding window</b> — ज़्यादा accurate और smooth।</li><li><b>Fixed window counter</b> — simple पर window के किनारों पर burst हो सकता है।</li></ul><p><b>Implementation:</b> counters <b>Redis</b> में रखो (fast, shared, atomic <code class='inline'>INCR</code> + TTL)। API gateway पर लगाओ। Limit पार होने पर HTTP <b>429</b> + <code class='inline'>Retry-After</code> लौटाओ।</p>"
},
{
  id: "sd-3", category: "System Design", difficulty: "medium",
  question: "Caching strategies and how to handle cache invalidation?",
  answerEn: "<p><b>Patterns:</b></p><ul><li><b>Cache-aside (lazy):</b> app checks cache; on miss, loads from DB and populates cache. Most common.</li><li><b>Write-through:</b> writes go to cache and DB together (consistent, slower writes).</li><li><b>Write-behind:</b> write to cache, async to DB (fast, risk of loss).</li></ul><p><b>Invalidation</b> is the hard part — options: set a <b>TTL</b> (expire after N seconds), <b>evict on write</b> (delete/update the key when data changes), or version keys. Watch for <b>cache stampede</b> (many misses at once) — mitigate with locks or staggered TTLs.</p>",
  answerHi: "<p><b>Patterns:</b></p><ul><li><b>Cache-aside (lazy):</b> app पहले cache देखे; miss पर DB से लाकर cache भरे। सबसे common।</li><li><b>Write-through:</b> write cache और DB दोनों में साथ (consistent, writes slow)।</li><li><b>Write-behind:</b> पहले cache में, फिर async DB में (fast पर loss का risk)।</li></ul><p><b>Invalidation</b> सबसे मुश्किल — options: <b>TTL</b> (कुछ सेकंड बाद expire), <b>write पर evict</b> (data बदलने पर key delete/update), या versioned keys। <b>Cache stampede</b> (एक साथ बहुत miss) से बचने के लिए lock या अलग-अलग TTL।</p>"
},

/* ============================ DSA ============================ */
{
  id: "dsa-1", category: "DSA", difficulty: "easy",
  question: "Explain Big-O notation and give common examples.",
  answerEn: "<p><b>Big-O</b> describes how an algorithm's time/space grows as input size n grows (worst case).</p><ul><li><b>O(1)</b> — constant (HashMap get).</li><li><b>O(log n)</b> — binary search.</li><li><b>O(n)</b> — single loop / linear scan.</li><li><b>O(n log n)</b> — good sorts (merge/quick sort).</li><li><b>O(n²)</b> — nested loops (avoid for large n).</li></ul><p>In interviews, always state the time <b>and</b> space complexity of your solution and whether it can be improved.</p>",
  answerHi: "<p><b>Big-O</b> बताता है कि input n बढ़ने पर algorithm का time/space कितना बढ़ता है (worst case)।</p><ul><li><b>O(1)</b> — constant (HashMap get)।</li><li><b>O(log n)</b> — binary search।</li><li><b>O(n)</b> — एक loop / linear scan।</li><li><b>O(n log n)</b> — अच्छे sorts (merge/quick)।</li><li><b>O(n²)</b> — nested loops (बड़े n के लिए avoid)।</li></ul><p>Interview में हमेशा time <b>और</b> space complexity बताओ और ये भी कि improve हो सकता है या नहीं।</p>"
},
{
  id: "dsa-2", category: "DSA", difficulty: "easy",
  question: "Find if an array has a pair summing to a target (Two Sum).",
  answerEn: "<p><b>Brute force</b> is O(n²) with two nested loops. The optimal approach uses a <b>HashMap</b> in a single pass — O(n) time, O(n) space.</p><p>For each number, check if <code class='inline'>target - num</code> was already seen; if yes, you found the pair; otherwise store the number. This 'complement in a hash set' pattern is one of the most common interview building blocks.</p>",
  answerHi: "<p><b>Brute force</b> O(n²) है (दो nested loops)। Best तरीका <b>HashMap</b> से एक ही pass में — O(n) time, O(n) space।</p><p>हर number के लिए check करो कि <code class='inline'>target - num</code> पहले दिखा या नहीं; अगर हाँ तो pair मिल गया; नहीं तो number store कर दो। ये 'complement in hash set' pattern बहुत common है।</p>",
  code: "int[] twoSum(int[] nums, int target) {\n    Map<Integer,Integer> seen = new HashMap<>();\n    for (int i = 0; i < nums.length; i++) {\n        int need = target - nums[i];\n        if (seen.containsKey(need)) return new int[]{seen.get(need), i};\n        seen.put(nums[i], i);\n    }\n    return new int[]{-1, -1};\n}"
},
{
  id: "dsa-3", category: "DSA", difficulty: "medium",
  question: "Which DSA patterns should you master for interviews?",
  answerEn: "<p>Most medium problems reduce to a handful of patterns — learn to recognize them:</p><ul><li><b>Two pointers</b> — sorted arrays, pairs, palindromes.</li><li><b>Sliding window</b> — subarray/substring with a constraint.</li><li><b>Hashing</b> — frequency counts, complements, dedup.</li><li><b>Binary search</b> — sorted data, 'search on answer'.</li><li><b>BFS/DFS</b> — trees and graphs.</li><li><b>Dynamic programming</b> — overlapping subproblems (knapsack, LIS).</li><li><b>Heap</b> — top-K, merge K lists.</li></ul><p>Practice ~40–50 problems, 1–2 daily. Recognizing the pattern beats memorizing solutions.</p>",
  answerHi: "<p>ज़्यादातर medium problems कुछ ही patterns पर आधारित होती हैं — इन्हें पहचानना सीखो:</p><ul><li><b>Two pointers</b> — sorted arrays, pairs, palindrome।</li><li><b>Sliding window</b> — constraint वाले subarray/substring।</li><li><b>Hashing</b> — frequency count, complement, dedup।</li><li><b>Binary search</b> — sorted data।</li><li><b>BFS/DFS</b> — trees और graphs।</li><li><b>Dynamic programming</b> — overlapping subproblems।</li><li><b>Heap</b> — top-K, merge K lists।</li></ul><p>रोज़ 1–2 करके ~40–50 problems करो। Solution रटने से बेहतर है pattern पहचानना।</p>"
},

/* ============================ BEHAVIORAL ============================ */
{
  id: "beh-1", category: "Behavioral & Leadership", difficulty: "medium",
  question: "Tell me about yourself. (2-minute pitch)",
  answerEn: "<p>Use <b>Present → Past → Future</b>:</p><ul><li><b>Present:</b> \"I'm a full-stack engineer and Project Lead with 4+ years, currently leading a team of 7 on Tendable, a healthcare quality-inspection platform.\"</li><li><b>Past:</b> \"Before that I spent ~3 years building Java/Spring Boot microservices for Bancstac, a payment platform integrating major card networks with 3DS and PCI DSS — I cut gateway latency ~20%.\"</li><li><b>Future:</b> \"I'm looking for a role where I can combine backend depth with technical leadership on high-scale systems.\"</li></ul><p>Keep it ~90 seconds, tailored to the job. Lead with impact, not a task list.</p>",
  answerHi: "<p><b>Present → Past → Future</b> formula use करो:</p><ul><li><b>Present:</b> \"मैं full-stack engineer और Project Lead हूँ, 4+ साल अनुभव, अभी Tendable पर 7 लोगों की team lead कर रहा हूँ।\"</li><li><b>Past:</b> \"उससे पहले ~3 साल Bancstac payment platform पर Java/Spring Boot microservices बनाए — card networks, 3DS, PCI DSS; gateway latency ~20% घटाई।\"</li><li><b>Future:</b> \"अब ऐसा role चाहता हूँ जहाँ backend की depth और technical leadership दोनों use कर सकूँ।\"</li></ul><p>~90 सेकंड, job के हिसाब से। काम की list नहीं, impact बताओ।</p>"
},
{
  id: "beh-2", category: "Behavioral & Leadership", difficulty: "medium",
  question: "Describe a challenging technical problem you solved. (STAR)",
  answerEn: "<p>Use <b>STAR</b>: Situation, Task, Action, Result.</p><ul><li><b>S:</b> \"Our payment gateway had latency spikes under load, risking timeouts on card transactions.\"</li><li><b>T:</b> \"I owned reducing latency without compromising reliability or PCI compliance.\"</li><li><b>A:</b> \"I profiled the flow, found synchronous calls and N+1 queries, introduced async processing via RabbitMQ, added Redis caching and query tuning, and set up circuit breakers on external calls.\"</li><li><b>R:</b> \"Latency dropped ~20% and the system stayed stable at peak load.\"</li></ul><p>Quantify the result and emphasize <b>your</b> specific actions.</p>",
  answerHi: "<p><b>STAR</b> use करो: Situation, Task, Action, Result।</p><ul><li><b>S:</b> \"हमारे payment gateway में load पर latency spikes आते थे, transactions timeout होने का risk था।\"</li><li><b>T:</b> \"reliability और PCI compliance बनाए रखते हुए latency घटाना मेरी ज़िम्मेदारी थी।\"</li><li><b>A:</b> \"मैंने flow profile किया, synchronous calls और N+1 queries पकड़े, RabbitMQ से async processing लाया, Redis caching और query tuning की, external calls पर circuit breaker लगाया।\"</li><li><b>R:</b> \"Latency ~20% घटी और system peak load पर stable रहा।\"</li></ul><p>Result को numbers में बताओ और <b>अपने</b> actions पर ज़ोर दो।</p>"
},
{
  id: "beh-3", category: "Behavioral & Leadership", difficulty: "medium",
  question: "How do you handle conflict within your team?",
  answerEn: "<p>Show maturity and a process, not just 'I stay calm':</p><ul><li>Listen to both sides <b>1:1</b> first to understand the real concern (often it's not the surface issue).</li><li>Bring it back to <b>shared goals</b> and data/facts rather than opinions.</li><li>For technical disagreements, evaluate trade-offs objectively — sometimes prototype both and let results decide.</li><li>Disagree and commit: once a decision is made, the team aligns.</li></ul><p>Give a real example from leading your team of 7 — e.g. a code-review or architecture disagreement you resolved.</p>",
  answerHi: "<p>सिर्फ़ 'मैं calm रहता हूँ' नहीं — एक process दिखाओ:</p><ul><li>पहले दोनों से <b>अलग-अलग (1:1)</b> बात करके असली दिक्कत समझो।</li><li>बात को opinions की जगह <b>common goals</b> और data/facts पर लाओ।</li><li>Technical disagreement में trade-offs objectively देखो — कभी-कभी दोनों approach prototype करके result से तय करो।</li><li>Disagree and commit: फ़ैसला हो जाए तो पूरी team उसके साथ align हो।</li></ul><p>अपनी 7 लोगों की team से एक real example दो — जैसे कोई code-review या architecture disagreement जो आपने सुलझाया।</p>"
},
{
  id: "beh-4", category: "Behavioral & Leadership", difficulty: "medium",
  question: "How did you handle a production incident or tight deadline?",
  answerEn: "<p><b>For an incident</b> show a calm, systematic approach:</p><ul><li><b>Mitigate first</b> — restore service (rollback, failover, scale) before root-causing.</li><li><b>Communicate</b> — keep stakeholders updated with clear status.</li><li><b>Root cause</b> — investigate logs/metrics/traces after stability.</li><li><b>Prevent</b> — add monitoring, alerts, tests, and a blameless post-mortem.</li></ul><p><b>For a tight deadline:</b> scope ruthlessly (MVP first), communicate risk early, parallelize work across the team, and protect quality on the critical path.</p>",
  answerHi: "<p><b>Incident में</b> calm और systematic रहो:</p><ul><li><b>पहले mitigate करो</b> — service वापस लाओ (rollback, failover, scale), root cause बाद में।</li><li><b>Communicate करो</b> — stakeholders को साफ़ status देते रहो।</li><li><b>Root cause</b> — stability के बाद logs/metrics/traces देखो।</li><li><b>Prevent</b> — monitoring, alerts, tests जोड़ो और blameless post-mortem करो।</li></ul><p><b>Tight deadline में:</b> scope छोटा रखो (MVP पहले), risk जल्दी बताओ, काम team में parallel बाँटो, और critical path पर quality बचाओ।</p>"
},
{
  id: "beh-5", category: "Behavioral & Leadership", difficulty: "easy",
  question: "Why are you leaving / looking for a new role?",
  answerEn: "<p>Stay <b>positive</b> — never bad-mouth your current employer. Frame it as growth:</p><p>\"I've grown a lot at Innostax — from engineer to Project Lead — and I'm grateful for it. I'm now looking for a larger-scale environment where I can deepen my backend and system-design work and take on bigger technical ownership.\"</p><p>Focus on what you're moving <b>toward</b>, not away from.</p>",
  answerHi: "<p><b>Positive</b> रहो — current company की बुराई कभी मत करो। इसे growth की तरह पेश करो:</p><p>\"Innostax में मैंने बहुत सीखा — engineer से Project Lead तक पहुँचा, और आभारी हूँ। अब बड़े scale के environment की तलाश है जहाँ backend और system-design में और गहराई और बड़ी technical ownership मिले।\"</p><p>किससे भाग रहे हो नहीं, किसकी <b>ओर</b> जा रहे हो उस पर focus करो।</p>"
},
{
  id: "beh-6", category: "Behavioral & Leadership", difficulty: "medium",
  question: "How do you use AI tools (Cursor, Claude) in your workflow?",
  answerEn: "<p>Show you use AI as a <b>force multiplier</b>, not a crutch:</p><ul><li><b>Speed:</b> scaffolding boilerplate, writing tests, drafting docs, exploring unfamiliar APIs.</li><li><b>Quality:</b> AI-assisted code review to catch bugs and suggest cleaner approaches before human review.</li><li><b>Judgment:</b> \"I always review and understand generated code — I never merge what I can't explain or verify, especially in payment/security-sensitive code.\"</li></ul><p>Mention building/configuring agents and prompt engineering (from your resume) as a concrete edge.</p>",
  answerHi: "<p>दिखाओ कि AI को <b>force multiplier</b> की तरह use करते हो, crutch की तरह नहीं:</p><ul><li><b>Speed:</b> boilerplate, tests, docs, नई APIs explore करना।</li><li><b>Quality:</b> human review से पहले AI-assisted code review से bugs पकड़ना।</li><li><b>Judgment:</b> \"generated code हमेशा समझकर review करता हूँ — जो explain/verify न कर सकूँ वो merge नहीं करता, खासकर payment/security code में।\"</li></ul><p>Agents बनाना/configure करना और prompt engineering (आपके resume से) एक ठोस edge के तौर पर बताओ।</p>"
},
{
  id: "beh-7", category: "Behavioral & Leadership", difficulty: "medium",
  question: "How do you make the transition from engineer to lead? What changed?",
  answerEn: "<p>Show self-awareness about the shift from <b>individual output</b> to <b>team output</b>:</p><ul><li>Success is now measured by what the <b>team</b> ships, not just my own code.</li><li>I spend more time on <b>unblocking, mentoring, code review, and planning</b>, and I protect focus time for the team.</li><li>I still stay hands-on enough to make sound architectural calls and earn technical credibility.</li><li>The hardest lesson: <b>delegating</b> and trusting the team instead of doing everything myself.</li></ul>",
  answerHi: "<p><b>अपने output</b> से <b>team के output</b> की तरफ़ shift की समझ दिखाओ:</p><ul><li>अब success सिर्फ़ मेरे code से नहीं, <b>team</b> क्या ship करती है उससे मापा जाता है।</li><li>ज़्यादा समय <b>unblocking, mentoring, code review, planning</b> में जाता है और team का focus time बचाता हूँ।</li><li>Architecture के सही फ़ैसले और technical credibility के लिए hands-on भी रहता हूँ।</li><li>सबसे मुश्किल सीख: <b>delegate करना</b> और team पर भरोसा करना, सब खुद न करना।</li></ul>"
}

];
